import { redactSensitiveContent, scanSensitiveContent } from '../workspace/sensitive-content.js';

export const INVESTIGATION_EXPERIENCE_VERSION = 1;
export const INVESTIGATION_PHASES = Object.freeze(['symptom','evidence','interpret','branch','action','verify','recover']);
export const COMMAND_RISKS = Object.freeze(['read-only','reversible','service-impacting','destructive']);
export const BRANCH_FEEDBACK = Object.freeze(['solved','did-not-solve','missing-scenario','guidance-outdated']);

export const roleProfiles = Object.freeze({
  'on-call': { label:'On-call', recommendation:'Start with blast radius, recent changes, and the fastest read-only discriminator.', firstJourney:'journey-kubernetes-image-pull-backoff', priorities:['kubernetes','networking','http'], tools:['Universal Input','Incident Brief'], references:['kubectl reference','HTTP status reference'] },
  learning: { label:'Learning', recommendation:'Read the evidence interpretation before choosing a branch or command.', firstJourney:'journey-linux-permission-denied', priorities:['linux','docker','kubernetes'], tools:['Command reference','Evidence interpreters'], references:['Linux permissions','Kubernetes concepts'] },
  incident: { label:'Incident response', recommendation:'Preserve timestamps and observations, record scope, and prepare a redacted handoff.', firstJourney:'journey-networking-connection-timeout', priorities:['networking','http','kubernetes'], tools:['Incident Brief','Universal Input'], references:['HTTP status reference','Networking checks'] },
  configuration: { label:'Configuration review', recommendation:'Validate syntax and effective configuration before applying a change.', firstJourney:'journey-terraform-init-provider-failure', priorities:['terraform','yaml','docker'], tools:['Configuration checkers','Diff viewer'], references:['Terraform CLI','YAML reference'] }
});

export const roleStartingPoints = Object.freeze([
  {id:'on-call',label:"I'm on-call",description:'Start with fast triage, risk, rollback, and escalation.',href:'/troubleshoot/?role=on-call'},
  {id:'learning',label:"I'm learning",description:'Understand evidence before choosing a change.',href:'/troubleshoot/?role=learning'},
  {id:'incident',label:"I'm investigating an incident",description:'Preserve evidence and build a local handoff.',href:'/troubleshoot/?role=incident'},
  {id:'configuration',label:"I'm reviewing configuration",description:'Use deterministic, browser-local configuration checks.',href:'/tools/?role=configuration'}
]);

export const environmentOptions = Object.freeze({cloud:['','AWS','Azure','GCP','Other or private cloud'],kubernetes:['','Amazon EKS','Azure AKS','Google GKE','OpenShift','Self-managed'],operatingSystem:['','Linux','macOS','Windows','Container image','Unknown'],proxy:['','No proxy known','HTTP or HTTPS proxy','Private egress gateway','Unknown'],registry:['','Public registry','Private registry','Cloud-managed registry','Unknown']});
const text=(value,max=40000)=>typeof value==='string'?value.slice(0,max):'';
const list=value=>Array.isArray(value)?value:[];
export function normalizeEnvironmentContext(value={}){return {cloud:text(value.cloud,80),kubernetes:text(value.kubernetes,80),operatingSystem:text(value.operatingSystem,80),versions:text(value.versions,240),proxy:text(value.proxy,80),registry:text(value.registry,80)};}
export function narrowGuidance(items=[],context={}){const normalized=normalizeEnvironmentContext(context);return list(items).filter(item=>!item?.environments||Object.entries(item.environments).every(([key,accepted])=>!normalized[key]||list(accepted).includes(normalized[key])));}
export function resolveRole(value){return roleProfiles[value]?value:'on-call';}
export function prioritizeJourneysForRole(journeys=[],value){const profile=roleProfiles[resolveRole(value)];const score=item=>item.id===profile.firstJourney?-100:(profile.priorities.includes(item.domain)?profile.priorities.indexOf(item.domain):99);return [...journeys].sort((a,b)=>score(a)-score(b));}

const contextRules=Object.freeze([
  {id:'private-registry',matches:c=>/private|cloud-managed/i.test(c.registry),branchTerms:['authentication','credential','registry','pull'],recommendation:'Confirm the workload identity or image-pull secret is authorized for the named registry.',command:'Inspect the workload event and registry host before testing credentials.',prerequisite:'Read access to workload events and registry metadata; do not paste credentials.',reference:{label:'Open image-pull troubleshooting',path:'/troubleshoot/kubernetes/image-pull-backoff/'},related:{label:'Open Kubernetes troubleshooting',path:'/troubleshoot/kubernetes/'}},
  {id:'proxy',matches:c=>/proxy|egress gateway/i.test(c.proxy),branchTerms:['timeout','tls','proxy','dns'],recommendation:'Check whether the request used the expected proxy or egress path; this does not prove the proxy is causal.',command:'Inspect proxy environment and a verbose read-only request with secrets removed.',prerequisite:'Know the approved proxy endpoint and redaction policy.',reference:{label:'Open connection-timeout troubleshooting',path:'/troubleshoot/networking/connection-timeout/'},related:{label:'Open TLS verification troubleshooting',path:'/troubleshoot/networking/tls-certificate-verification/'}},
  {id:'kubernetes',matches:c=>Boolean(c.kubernetes),branchTerms:['pod','service','endpoint','image','kubernetes'],recommendation:'Prefer cluster events, selectors, endpoints, and workload status from the selected Kubernetes environment.',command:'Run namespace-scoped kubectl get/describe commands against the intended context.',prerequisite:'Confirm kube-context, namespace, and read-only RBAC.',reference:{label:'Open Kubernetes troubleshooting',path:'/troubleshoot/kubernetes/'},related:{label:'Open Service-unreachable troubleshooting',path:'/troubleshoot/kubernetes/service-unreachable/'}},
  {id:'windows',matches:c=>c.operatingSystem==='Windows',branchTerms:['network','dns','permission'],recommendation:'Use the Windows-equivalent read-only command when a journey presents a Unix-only example.',command:'Confirm PowerShell or Windows-native command availability before running an example.',prerequisite:'Use a non-elevated shell unless the check explicitly requires more access.',reference:{label:'Open command reference',path:'/reference/'},related:{label:'Open networking troubleshooting',path:'/troubleshoot/networking/'}},
  {id:'cloud',matches:c=>['AWS','Azure','GCP'].includes(c.cloud),branchTerms:['identity','quota','network','credential'],recommendation:'Narrow identity, quota, network, and ownership checks to the selected cloud account, subscription, or project.',command:'Use read-only provider commands in the intended account and region, with secrets redacted.',prerequisite:'Confirm the active cloud identity and scope.',reference:{label:'Open Terraform provider troubleshooting',path:'/troubleshoot/terraform/init-provider-failure/'},related:{label:'Open operational starting points',path:'/troubleshoot/'} }
]);
export function environmentGuidance(context={}){const normalized=normalizeEnvironmentContext(context);const matches=contextRules.filter(rule=>rule.matches(normalized));return {recommendations:matches.map(x=>x.recommendation),commands:matches.map(x=>x.command),prerequisites:matches.map(x=>x.prerequisite),references:matches.map(x=>x.reference),relatedLinks:matches.map(x=>x.related),branchTerms:[...new Set(matches.flatMap(x=>x.branchTerms))],certainty:'Context narrows applicable checks only; confirm every branch using observed evidence.'};}

export function commandPrerequisites(command={},fallbackRisk='read-only'){const placeholders=[...new Set((String(command.command||'').match(/<[^>]+>/g)||[]))];const risk=COMMAND_RISKS.includes(command.risk)?command.risk:fallbackRisk==='read-only'?'read-only':fallbackRisk==='low-risk'?'reversible':fallbackRisk==='moderate-risk'?'service-impacting':'destructive';return {purpose:text(command.purpose)||'Collect evidence for the current decision.',permissions:text(command.permissions)||'Permission to read the named resource.',executionContext:text(command.executionContext)||'Run in the context named by the command.',platformAssumptions:text(command.platformAssumptions)||'Confirm the command is available and appropriate for your platform.',placeholders,expectedEvidence:text(command.expectedEvidence)||'Record output, error class, timestamp, and affected scope.',risk};}
export function buildEvidenceBundles(journey={}){const groups=Object.fromEntries(COMMAND_RISKS.map(risk=>[risk,[]]));for(const node of list(journey.nodes))for(const command of list(node.commands)){const meta=commandPrerequisites(command,node.risk);groups[meta.risk].push({command:text(command.command,4000),nodeTitle:text(node.title,200),...meta});}return groups;}
export function compareEvidence(before='',after='',criteria=[]){const left=text(before,12000).trim(),right=text(after,12000).trim();const checks=list(criteria).map(item=>typeof item==='string'?{label:item,checked:false}:{label:text(item?.label,500),checked:Boolean(item?.checked)}).filter(x=>x.label);const allConfirmed=checks.length>0&&checks.every(x=>x.checked);return {before:left,after:right,changed:Boolean(left&&right&&left!==right),status:!left||!right?'incomplete':allConfirmed?'criteria-confirmed':left===right?'not-demonstrated':'comparison-ready',criteria:checks,allConfirmed,reminder:'Changed output alone is not proof of recovery. Confirm each verification criterion in the target environment.'};}
export function createTimelineEntry(type,summary,detail='',now=new Date().toISOString()){const allowed=['observation','evidence','command','decision','action','rollback','verification','feedback'];return {id:`${now}-${Math.random().toString(36).slice(2,8)}`,type:allowed.includes(type)?type:'observation',summary:text(summary,500),detail:text(detail,4000),createdAt:now};}
export function normalizeTimeline(value){return list(value).slice(-100).map(item=>({id:text(item?.id,160)||String(Date.now()),type:text(item?.type,40)||'observation',summary:text(item?.summary,500),detail:text(item?.detail,4000),createdAt:text(item?.createdAt,40)||new Date().toISOString()}));}
export function redactForHandoff(value=''){const output=redactSensitiveContent(text(value));return {text:output,warnings:scanSensitiveContent(output)};}
const contextLines=environment=>Object.entries(normalizeEnvironmentContext(environment)).filter(([,value])=>value).map(([key,value])=>`${key}: ${value}`);
const timelineLines=timeline=>normalizeTimeline(timeline).map(item=>`${item.createdAt} · ${item.type}: ${item.summary}${item.detail?` — ${item.detail}`:''}`);
export function formatIncidentChannel({title,timeline,environment}){return [`Incident: ${title}`,'Context:',...(contextLines(environment).length?contextLines(environment):['Not recorded']),'Updates:',...(timelineLines(timeline).length?timelineLines(timeline):['No entries recorded'])].join('\n');}
export function formatTicket({title,timeline,environment}){return [`TITLE: ${title}`,'ENVIRONMENT:',...(contextLines(environment).map(x=>`- ${x}`)||[]),'ACCEPTANCE / VERIFICATION:',...normalizeTimeline(timeline).filter(x=>x.type==='verification').map(x=>`- ${x.summary}: ${x.detail}`),'INVESTIGATION LOG:',...timelineLines(timeline).map(x=>`- ${x}`)].join('\n');}
export function formatMarkdownReport({title,timeline,environment}){return `# ${title}\n\n## Environment\n\n${contextLines(environment).map(x=>`- ${x}`).join('\n')||'- Not recorded'}\n\n## Timeline\n\n${timelineLines(timeline).map(x=>`- ${x}`).join('\n')||'- No entries recorded'}\n`;}
export function formatCommandTranscript({title,timeline}){const commands=normalizeTimeline(timeline).filter(x=>x.type==='command');return [`Sanitized command transcript: ${title}`,...(commands.length?commands.map(x=>`$ ${x.detail||x.summary}`):['No copied commands recorded.'])].join('\n');}
export function buildInvestigationExport(input={}){const format=input.format||'markdown';const formatters={channel:formatIncidentChannel,ticket:formatTicket,markdown:formatMarkdownReport,transcript:formatCommandTranscript};const body=(formatters[format]||formatters.markdown)({title:input.title||'Investigation',timeline:input.timeline||[],environment:input.environment||{}});return {...redactForHandoff(body),format,reviewRequired:true};}
export const investigationStorageKey=journeyId=>`helpdevops.investigation.v1.${String(journeyId).replace(/[^a-z0-9_-]/gi,'-')}`;
export function clearInvestigationStorage(storage,journeyId){const prefix=investigationStorageKey(journeyId);const keys=[];for(let i=0;i<storage.length;i++){const key=storage.key(i);if(key&&(key===prefix||key.startsWith(`${prefix}.`)))keys.push(key);}keys.forEach(key=>storage.removeItem(key));return keys.every(key=>storage.getItem(key)===null);}