import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('Dockerfile analyzer reports structure and selected review notes',async({page})=>{await page.goto('/tools/dockerfile/');await page.locator('#dockerfile-input').fill('FROM ubuntu:latest\nUSER root\nCMD echo start');await page.getByRole('button',{name:'Inspect'}).click();await expect(page.getByText('Dockerfile inspected')).toBeVisible();await expect(page.locator('[data-analysis-result]')).toContainText('latest');await expect(page.locator('[data-analysis-result]')).toContainText('root')});

test('Compose analyzer inspects services without claiming runtime validation',async({page})=>{await page.goto('/tools/docker-compose/');await page.locator('#compose-input').fill('services:\n  web:\n    image: nginx:1.27-alpine');await page.getByRole('button',{name:'Inspect'}).click();await expect(page.getByText('Docker Compose file inspected')).toBeVisible();await expect(page.locator('[data-analysis-result]')).toContainText('not full Compose Specification validation')});

test('Kubernetes analyzer handles a workload and exposes cluster limits',async({page})=>{await page.goto('/tools/kubernetes-manifest/');await page.locator('#kubernetes-input').fill('apiVersion: v1\nkind: Pod\nmetadata: {name: web}\nspec:\n  containers:\n  - name: web\n    image: nginx:1.27-alpine');await page.getByRole('button',{name:'Inspect'}).click();await expect(page.getByText('Kubernetes manifests inspected')).toBeVisible();await expect(page.locator('[data-analysis-result]')).toContainText('does not connect to a cluster')});

test('Universal Input routes container and Kubernetes forms to specialized tools',async({page})=>{await page.goto('/');const input=page.locator('#universal-input'),analyze=page.getByRole('button',{name:/Analyze input/}),result=page.locator('[data-analysis-result]'),kind=page.locator('[data-result-kind]'),target=page.locator('[data-send-result]');const submit=async(value,expectedKind,expectedTarget)=>{await input.fill(value);await expect(input).toHaveValue(value);await analyze.click();await expect(result).toHaveAttribute('data-result-rendered-kind',expectedKind.toLowerCase());await expect(kind).toHaveText(expectedKind);await expect(target).toContainText(expectedTarget)};await submit('FROM alpine:3.21\nUSER 1000','DOCKERFILE','dockerfile');await submit('services:\n  web:\n    image: nginx:1.27','COMPOSE','docker compose');await submit('apiVersion: v1\nkind: ConfigMap\nmetadata: {name: x}','KUBERNETES','kubernetes manifest')});

test('EP-006 routes are accessible and reflow',async({page})=>{await page.setViewportSize({width:640,height:900});for(const route of ['/tools/dockerfile/','/tools/docker-compose/','/tools/kubernetes-manifest/']){await page.goto(route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);const result=await new AxeBuilder({page}).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([])}});
