import {test,expect} from '@playwright/test';
test('EP-012 homepage hierarchy and ambiguity stay truthful',async({page})=>{const external=[];page.on('request',request=>{if(!request.url().startsWith('http://127.0.0.1:4321/'))external.push(request.url())});await page.goto('/');await expect(page.getByRole('heading',{level:1})).toContainText('Find the safest next step');await page.locator('[data-analysis-context]').selectOption('command-output');await page.locator('[data-analysis-input]').fill('unsupported operational text');await page.locator('[data-analyze]').click();await expect(page.locator('[data-result-title]')).toContainText('not recognized');await expect(page.locator('[data-analysis-result]')).not.toContainText(/confidence|\d+%/i);expect(external).toEqual([])});
test('EP-012 Incident Brief defaults to summary and blocks private keys',async({page})=>{await page.goto('/incident-brief/');await page.locator('[name="summary"]').fill('API unavailable');await page.locator('[name="rawEvidence"]').fill('raw should stay excluded');await page.getByRole('button',{name:'Generate brief'}).click();await expect(page.locator('[data-brief-preview]')).toContainText('API unavailable');await expect(page.locator('[data-brief-preview]')).not.toContainText('raw should stay excluded');await page.locator('[name="brief-mode"][value="raw"]').check();await page.locator('[name="rawEvidence"]').fill('-----BEGIN PRIVATE KEY-----');await page.locator('[name="rawAcknowledged"]').check();await page.getByRole('button',{name:'Generate brief'}).click();await expect(page.locator('[data-brief-status]')).toContainText('cannot be included')});
test('EP-012 correction reporting attaches no user input',async({page})=>{await page.goto('/troubleshoot/');const details=page.locator('.correction-report');await details.locator('summary').click();await expect(details).toContainText('Nothing from this page or your input is attached automatically');await expect(details.locator('[data-copy-correction]')).toHaveAttribute('data-template',/Resource: \/troubleshoot\//)});


test('diagnostic completion transfers structured context to Incident Brief',async({page})=>{await page.goto('/troubleshoot/linux/disk-full/');let guard=0;while(await page.locator('[data-build-incident-brief]').isHidden()&&guard++<12){const choice=page.locator('[data-choice-list] button').first();if(!await choice.count())break;await choice.click()}await page.locator('[data-build-incident-brief]').click();await expect(page).toHaveURL(/incident-brief/);await expect(page.locator('[data-brief-status]')).toContainText('transferred');await expect(page.locator('[name="rawEvidence"]')).toHaveValue('')});

test('Incident Brief Markdown download remains non-empty',async({page})=>{await page.goto('/incident-brief/');await page.locator('[name="summary"]').fill('Download verification');await page.getByRole('button',{name:'Generate brief'}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download Markdown'}).click();const download=await downloadPromise;expect(await download.createReadStream()).toBeTruthy();expect(download.suggestedFilename()).toContain('download-verification')});
