import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';
const samples={
 df:'Filesystem Size Used Avail Use% Mounted on\n/dev/sda1 50G 49G 500M 99% /',
 kubernetes:JSON.stringify({kind:'Pod',metadata:{name:'api'},status:{phase:'Running',containerStatuses:[{name:'api',restartCount:4,state:{waiting:{reason:'CrashLoopBackOff'}},lastState:{terminated:{reason:'OOMKilled',exitCode:137}}}]}}),
 docker:JSON.stringify({Status:'exited',Running:false,OOMKilled:true,ExitCode:137}),
 terraform:'Error: Error acquiring the state lock\nLock Info:\n ID: 123\n Path: prod.tfstate\n Operation: Apply\n Who: ci@example.test',
 systemd:'Id=api.service\nLoadState=loaded\nActiveState=failed\nSubState=failed\nResult=exit-code\nExecMainStatus=1'
};
test('five evidence formats interpret locally',async({page})=>{await page.goto('/interpret/');for(const [source,input] of Object.entries(samples)){await page.locator('#evidence-source').selectOption(source==='df'?'df-usage':source==='kubernetes'?'kubernetes-pod':source==='docker'?'docker-state':source==='terraform'?'terraform-lock':'systemd-unit');await page.locator('#evidence-input').fill(input);await page.getByRole('button',{name:'Interpret'}).click();await expect(page.locator('[data-analysis-result]')).toBeVisible();await expect(page.locator('[data-result-not-checked] li').first()).toBeVisible();}});
test('Universal Input prefers structured evidence and transfers it',async({page})=>{await page.goto('/');await page.locator('#universal-input').fill(samples.docker);await page.getByRole('button',{name:/Analyze input/}).click();await expect(page.locator('[data-result-kind]')).toContainText('EVIDENCE');await page.locator('[data-send-result]').click();await expect(page).toHaveURL(/\/interpret\/$/);await expect(page.locator('#evidence-input')).toHaveValue(samples.docker);});
test('interpretation-only workspace omits raw evidence and restores summary',async({page})=>{await page.goto('/interpret/');await page.locator('#evidence-source').selectOption('terraform-lock');await page.locator('#evidence-input').fill(samples.terraform);await page.getByRole('button',{name:'Interpret'}).click();await page.locator('header [data-session-open]').click();await page.locator('[data-workspace-title-input]').fill('Lock evidence');await page.locator('[data-save-current-tool]').click();await page.goto('/workspace/');await page.locator('[data-workspace-open]').click();await expect(page).toHaveURL(/\/interpret\/$/);await expect(page.locator('#evidence-input')).toHaveValue('');await expect(page.locator('[data-analysis-result]')).toContainText('Raw evidence was not saved');});
test('evidence routes are accessible and reflow',async({page})=>{await page.setViewportSize({width:640,height:900});for(const route of ['/interpret/','/interpret/df/','/interpret/kubernetes-pod/','/interpret/docker-container/','/interpret/terraform-lock/','/interpret/systemd-status/']){await page.goto(route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);const result=await new AxeBuilder({page}).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);}});
