import {describe,it,expect} from 'vitest';import {readFileSync} from 'node:fs';import {analyzeInput} from '../src/core/analyze-input.js';import {createIncidentBrief,briefToMarkdown,safeBriefFilename} from '../src/incident-brief/brief.js';
describe('EP-012 product cohesion',()=>{
 it('uses truthful context hints without fabricated confidence',()=>{const result=analyzeInput('not supported output','command-output');expect(result.status).toBe('unsupported');expect(result.summary).toContain('not forced');expect(JSON.stringify(result)).not.toMatch(/confidence|\d+%/i)});
 it('offers multiple supported lookup paths for reference context',()=>{const result=analyzeInput('systemd status','reference');expect(result.status).toBe('ambiguous');expect(result.related).toEqual(['/reference/','/errors/'])});
 it('excludes raw evidence by default',()=>{const brief=createIncidentBrief({summary:'API incident',rawEvidence:'internal log'},'summary');expect(brief.rawEvidence).toBe('');expect(briefToMarkdown(brief)).not.toContain('internal log')});
 it('requires acknowledgement and blocks private keys',()=>{expect(()=>createIncidentBrief({rawEvidence:'token=abc'},'raw')).toThrow(/acknowledge/);expect(()=>createIncidentBrief({rawEvidence:['-----BEGIN','PRIVATE KEY-----'].join(' ')},'raw',true)).toThrow(/Private-key/)});
 it('uses safe portable filenames and neutralizes formula-like lines',()=>{expect(safeBriefFilename('../../=SUM(A1)')).toBe('sum-a1-incident-brief.md');const text=briefToMarkdown(createIncidentBrief({summary:'=cmd'},'summary'));expect(text).toContain("'=cmd")});
 it('publishes the primary hierarchy and unique title',()=>{const home=readFileSync('src/pages/index.astro','utf8');expect(home).toContain('Find the safest next step');expect(home).toContain('Analyze Evidence');const brief=readFileSync('src/pages/incident-brief.astro','utf8');expect(brief).toContain('Summary only (recommended)')});

 it('uses the Next Action Layer in real shared result rendering',()=>{const ui=readFileSync('src/components/UniversalInput.astro','utf8');const result=readFileSync('src/components/results/AnalysisResult.astro','utf8');expect(ui).toContain('withNextActionLayer(result)');expect(result).toContain('data-result-meaning');expect(result).toContain('data-result-verification')});
 it('publishes provenance from resource-backed templates',()=>{for(const file of ['src/pages/troubleshoot/[domain]/[slug].astro','src/pages/interpret/[slug].astro','src/pages/reference/[slug].astro'])expect(readFileSync(file,'utf8')).toContain('ProvenanceStrip')});
 it('makes the legacy references route truthful',()=>{const route=readFileSync('src/pages/references.astro','utf8');expect(route).toContain('References moved');expect(route).toContain('/reference/');expect(route).not.toContain('publishing has not started')});
 it('connects diagnostics, interpreters and compatible workspaces to Incident Brief safely',()=>{const diagnostic=readFileSync('src/components/diagnostics/DiagnosticJourney.astro','utf8');const interpreter=readFileSync('src/pages/interpret/index.astro','utf8');const workspace=readFileSync('src/scripts/workspace-client.js','utf8');for(const source of [diagnostic,interpreter,workspace])expect(source).toContain('helpdevops.incident-brief-transfer.v1');const brief=readFileSync('src/pages/incident-brief.astro','utf8');expect(brief).toContain('contractVersion!==1');expect(brief).toContain("rawEvidence.value=''")});
 it('delays Blob URL revocation and neutralizes every formula-like line',()=>{const page=readFileSync('src/pages/incident-brief.astro','utf8');expect(page).toContain('60000');const text=briefToMarkdown(createIncidentBrief({summary:'ok',unknowns:'=one\n+two'},'summary'));expect(text).toContain("'=one");expect(text).toContain("'+two")});
 it('keeps release health browser claims deferred',()=>{const script=readFileSync('scripts/verify-release.mjs','utf8');expect(script).toContain('full Playwright browser matrix');expect(script).toContain('deferred')});
 it('does not transfer raw Universal Input into summary-only Incident Brief fields',()=>{const ui=readFileSync('src/components/UniversalInput.astro','utf8');expect(ui).not.toContain('symptom:inputText');expect(ui).toContain('symptom:result.summary')});
 it('scans the complete Incident Brief payload and blocks private keys outside raw evidence',()=>{expect(()=>createIncidentBrief({summary:['-----BEGIN','PRIVATE KEY-----'].join(' ')},'summary')).toThrow(/Private-key/);const brief=createIncidentBrief({symptom:'Owner: alice@example.com',observations:'Path: s3://company-prod-state/team/prod.tfstate'},'structured');expect(brief.sensitivity.warnings.map(x=>x.id)).toEqual(expect.arrayContaining(['email-address','terraform-state-path']))});
 it('anchors diagnostic limitations on visible content',()=>{const component=readFileSync('src/components/diagnostics/DiagnosticJourney.astro','utf8');const route=readFileSync('src/pages/troubleshoot/[domain]/[slug].astro','utf8');expect(component).toContain('<section id="limitations"><h3>What this does not prove</h3>');expect(route).not.toContain('<div id="limitations"></div>')});
 it('keeps the legacy references route out of sitemap and canonicalizes to the reviewed library',()=>{const config=readFileSync('astro.config.mjs','utf8');const route=readFileSync('src/pages/references.astro','utf8');expect(config).toContain("!page.endsWith('/references/')");expect(route).toContain('canonicalPath="/reference/"')});
 it('renders validated internal Next Action destinations as links',()=>{for(const file of ['src/components/UniversalInput.astro','src/pages/interpret/index.astro']){const source=readFileSync(file,'utf8');expect(source).toContain("document.createElement('a')");expect(source).toContain('a.href=path')}});
});

