import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import path from 'node:path';
import {publishedJourneys,diagnosticDomains} from '../src/diagnostics/registry.js';
import {navigation,site} from '../src/config/site.js';
const root=process.cwd();
const priority=['journey-docker-network-connectivity','journey-kubernetes-image-pull-backoff','journey-kubernetes-service-unreachable','journey-terraform-init-provider-failure','journey-networking-connection-timeout','journey-networking-tls-certificate'];
const mojibake=[String.fromCodePoint(0xc2),String.fromCodePoint(0xc3,0x201a),String.fromCodePoint(0xe2,0x20ac),String.fromCodePoint(0xe2,0x2020),String.fromCodePoint(0xc3,0x192)];
function textFiles(directory){return fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{const absolute=path.join(directory,entry.name);return entry.isDirectory()?textFiles(absolute):entry.isFile()&&fs.statSync(absolute).size<2_000_000?[absolute]:[]})}
describe('EP-018 troubleshooting platform',()=>{
 it('publishes the expanded unique journey registry',()=>{expect(publishedJourneys).toHaveLength(37);expect(new Set(publishedJourneys.map(x=>x.id)).size).toBe(37)});
 it('keeps every journey connected and safe',()=>{for(const j of publishedJourneys){expect(j.firstChecks.length).toBeGreaterThan(0);expect(j.references.some(r=>r.url.startsWith('https://'))).toBe(true);expect(j.nodes.some(n=>n.nodeKind==='action'&&n.rollback)).toBe(true);expect(j.nodes.some(n=>n.nodeKind==='verification'&&n.verification?.length)).toBe(true);expect(j.nodes.some(n=>n.nodeKind==='completion'&&n.prevention?.length)).toBe(true)}});
 it('adds observed-evidence branches to the six priority journeys',()=>{for(const id of priority){const journey=publishedJourneys.find(item=>item.id===id);const collect=journey.nodes.find(node=>node.id.endsWith('-collect'));expect(collect.choices.length,id).toBeGreaterThanOrEqual(4);expect(collect.choices.map(choice=>choice.id),id).not.toContain('cause-found');for(const choice of collect.choices.filter(item=>item.id!=='unclear')){const branch=journey.nodes.find(node=>node.id===choice.nextNodeId);expect(branch.nodeKind,id).toBe('interpretation');expect(branch.commands?.length,id).toBeGreaterThan(0)}}});
 it('uses local documented official-color technology marks',()=>{const expected={docker:'#2496ED',kubernetes:'#326CE5',terraform:'#7B42BC',git:'#F05032',bash:'#4EAA25',yaml:'#CB171E',jenkins:'#D33833',networking:'#00A4EF'};for(const [id,color] of Object.entries(expected)){const svg=fs.readFileSync(path.join(root,'public/icons/technologies',`${id}.svg`),'utf8');expect(svg,id).toContain(color);expect(svg,id).not.toContain('#00e887')}const linux=fs.readFileSync(path.join(root,'public/icons/technologies/linux.svg'),'utf8');expect(linux).toContain('#F5C400');expect(fs.existsSync(path.join(root,'docs/TECHNOLOGY-MARK-SOURCES.md'))).toBe(true)});
 it('contains no common mojibake signatures in release text sources',()=>{const files=['src','tests','docs','scripts','public'].flatMap(dir=>textFiles(path.join(root,dir)));const failures=[];for(const file of files){const text=fs.readFileSync(file,'utf8');if(mojibake.some(fragment=>text.includes(fragment)))failures.push(path.relative(root,file))}expect(failures).toEqual([])});
 it('covers the existing priority domains',()=>expect(diagnosticDomains).toEqual(expect.arrayContaining(['linux','docker','kubernetes','terraform','git','jenkins','cron','networking','bash','yaml'])));
 it('uses focused navigation and EP metadata',()=>{expect(navigation.map(x=>x.label)).toEqual(['Troubleshoot','Tools','Interpret','Workspace']);expect(site.version).toBe('0.20.0');expect(site.ep).toBe('EP-020')});
});
