import {describe,it,expect} from 'vitest';import {interpretEvidence} from '../src/core/evidence/interpreter.js';
describe('EP-009 evidence interpreters',()=>{
 it('parses df block usage',()=>{const r=interpretEvidence('Filesystem Size Used Avail Use% Mounted on\n/dev/sda1 50G 49G 500M 99% /');expect(r.parserId).toBe('df-usage');expect(r.unknowns.length).toBeGreaterThan(0)});
 it('parses df inode usage',()=>expect(interpretEvidence('Filesystem Inodes IUsed IFree IUse% Mounted on\n/dev/sda1 1000 999 1 99% /').parserId).toBe('df-usage'));
 it('parses Kubernetes Pod JSON',()=>{const r=interpretEvidence(JSON.stringify({kind:'Pod',metadata:{name:'api'},status:{phase:'Running',containerStatuses:[{name:'api',restartCount:3,state:{waiting:{reason:'CrashLoopBackOff'}},lastState:{terminated:{reason:'OOMKilled',exitCode:137}}}]}}));expect(r.parserId).toBe('kubernetes-pod');expect(r.interpretations.some(x=>/OOMKilled/.test(x.message))).toBe(true)});
 it('does not treat lone OOMKilled as structured evidence',()=>expect(interpretEvidence('OOMKilled').status).toBe('unsupported'));
 it('parses Docker State JSON',()=>{const r=interpretEvidence(JSON.stringify({Status:'exited',Running:false,OOMKilled:true,ExitCode:137}));expect(r.parserId).toBe('docker-state');expect(r.unknowns.length).toBeGreaterThan(0)});
 it('does not echo unrelated Docker inspect configuration',()=>{const r=interpretEvidence(JSON.stringify({State:{Status:'exited',ExitCode:1},Config:{Env:['TOKEN=secret']}}));expect(r.formatted).not.toContain('TOKEN')});
 it('parses Terraform lock blocks',()=>{const r=interpretEvidence('Error: Error acquiring the state lock\nLock Info:\n ID: 123\n Path: prod.tfstate\n Operation: Apply\n Who: ci@example.test');expect(r.parserId).toBe('terraform-lock');expect(r.interpretations[0].message).not.toMatch(/stale/i)});
 it('does not confuse dependency lock files',()=>expect(interpretEvidence('Edit .terraform.lock.hcl to change provider selections').status).toBe('unsupported'));
 it('parses systemctl show properties',()=>{const r=interpretEvidence('Id=api.service\nLoadState=loaded\nActiveState=failed\nSubState=failed\nResult=exit-code\nExecMainStatus=1');expect(r.parserId).toBe('systemd-unit');expect(r.unknowns.length).toBeGreaterThan(0)});
 it('requires source for ambiguous fragments',()=>expect(interpretEvidence('Status: Exited (1)').status).toBe('unsupported'));

 it('auto-detects POSIX df -P output without matching unrelated percentage tables',()=>{const posix=interpretEvidence('Filesystem 1024-blocks Used Available Capacity Mounted on\n/dev/sda1 100000 99000 1000 99% /');expect(posix.parserId).toBe('df-usage');expect(posix.recognition.format).toBe('df-posix');expect(interpretEvidence('Name Total Capacity\napi 10 99%').status).toBe('unsupported')});
 it('does not classify generic JSON as Docker state',()=>{expect(interpretEvidence(JSON.stringify({Status:'failed'})).status).toBe('unsupported');expect(interpretEvidence(JSON.stringify({Status:'healthy',Service:'api'})).status).toBe('unsupported')});
 it('parses a Docker formatted list JSON record',()=>{const r=interpretEvidence(JSON.stringify({ID:'abc123',Image:'nginx:1.27',Names:'web',Status:'Exited (1) 5 minutes ago'}));expect(r.parserId).toBe('docker-state');expect(r.recognition.format).toBe('docker-ps-json')});
 it('extracts current and previous Kubernetes termination fields distinctly',()=>{const r=interpretEvidence(JSON.stringify({kind:'Pod',metadata:{name:'job'},status:{phase:'Failed',containerStatuses:[{name:'job',restartCount:1,state:{terminated:{reason:'Error',exitCode:2,signal:9}},lastState:{terminated:{reason:'OOMKilled',exitCode:137,signal:0}}}]}}));expect(r.observations).toEqual(expect.arrayContaining([{label:'container job current exit code',value:'2'},{label:'container job current signal',value:'9'},{label:'container job previous exit code',value:'137'},{label:'container job previous signal',value:'0'}]))});
 it('limits Kubernetes status entries to fifty',()=>{const statuses=Array.from({length:55},(_,i)=>({name:`c${i}`,restartCount:0,state:{waiting:{reason:'ContainerCreating'}}}));const r=interpretEvidence(JSON.stringify({kind:'Pod',metadata:{name:'many'},status:{phase:'Pending',containerStatuses:statuses}}));expect(r.recognition.statusEntriesParsed).toBe(50);expect(r.recognition.statusEntriesTotal).toBe(55);expect(r.unknowns.some(x=>/first 50/.test(x))).toBe(true)});
 it('rejects oversized input',()=>expect(interpretEvidence('x'.repeat(70000)).status).toBe('invalid'));
 it('supports explicit source selection without bypassing validation',()=>expect(interpretEvidence('not df',{source:'df-usage'}).status).toBe('unsupported'));
});
