import YAML from 'yaml';
import resources from './resources.json';
const isObj=v=>v&&typeof v==='object'&&!Array.isArray(v);
const secretKey=/password|passwd|secret|token|api[_-]?key|private[_-]?key/i;
function imageNote(image){if(typeof image!=='string'||image.includes('@sha256:'))return null;const last=image.split('/').at(-1);return !last.includes(':')||last.endsWith(':latest')?'uses an unpinned or latest image reference':null;}
function envEntries(value){if(Array.isArray(value))return value.map(v=>String(v));if(isObj(value))return Object.entries(value).map(([k,v])=>`${k}=${v??''}`);return [];}
export function analyzeCompose(raw){
 const base={kind:'compose',evidence:[],findings:[],actions:[{label:'Review service findings',type:'review'}],checked:['YAML parsing','Top-level Compose structure','Service image/build declarations','Selected privilege, host-access, volume and environment signals'],notChecked:resources.limitations,references:resources.references,nextActions:['Run docker compose config with the intended environment files.','Test the resolved project in an isolated environment.']};
 if(!raw.trim())return {...base,status:'invalid',title:'No Compose file supplied',summary:'Paste a Compose YAML document.',actions:[]};
 if(new Blob([raw]).size>262144)return {...base,status:'unsupported',title:'Compose input is larger than 256 KB',summary:'Reduce the file before local inspection.',actions:[]};
 try{const docs=YAML.parseAllDocuments(raw,{maxAliasCount:100,prettyErrors:true});const errors=docs.flatMap(d=>d.errors);if(errors.length)throw errors[0];if(docs.length!==1)return {...base,status:'unsupported',title:'Expected one Compose document',summary:'Inspect one Compose project document at a time.',actions:[]};const value=docs[0].toJS({maxAliasCount:100});if(!isObj(value))throw new Error('Compose root must be a mapping.');const findings=[];if('version'in value)findings.push('Top-level version is obsolete under the current rolling Compose Specification and is retained only for compatibility.');if(!isObj(value.services)||!Object.keys(value.services).length)return {...base,status:'invalid',title:'Compose services mapping is missing',summary:'A Compose application requires a non-empty top-level services mapping.',findings,actions:[]};
 const services=Object.entries(value.services);for(const [name,service] of services){if(!isObj(service)){findings.push(`Service ${name}: definition is not a mapping.`);continue;}if(!service.image&&!service.build&&!service.extends)findings.push(`Service ${name}: no image, build, or extends source is declared.`);const note=imageNote(service.image);if(note)findings.push(`Service ${name}: ${note} (${service.image}).`);if(service.privileged===true)findings.push(`Service ${name}: privileged mode grants broad host capabilities.`);if(['host','service:'].some(v=>String(service.network_mode||'').startsWith(v)))findings.push(`Service ${name}: network_mode ${service.network_mode} requires environment-specific review.`);if(['host','container:'].some(v=>String(service.pid||'').startsWith(v)))findings.push(`Service ${name}: pid mode ${service.pid} shares another process namespace.`);if(['0','root','0:0','root:root'].includes(String(service.user||'').toLowerCase()))findings.push(`Service ${name}: user is explicitly root.`);for(const entry of envEntries(service.environment))if(secretKey.test(entry)&&!/^\w+=\$\{[^}]+\}$/.test(entry))findings.push(`Service ${name}: environment contains a secret-like literal (${entry.split('=')[0]}=••••).`);for(const volume of service.volumes||[]){const text=typeof volume==='string'?volume:JSON.stringify(volume);if(text.includes('/var/run/docker.sock'))findings.push(`Service ${name}: mounts the Docker socket, which can provide host-level control.`);if(/^\s*\/(?:[^:]+):/.test(text))findings.push(`Service ${name}: uses a host bind mount (${text.slice(0,100)}). Verify host path and permissions.`);}}
 const formatted=docs[0].toString({indent:2});return {...base,status:findings.length?'valid-with-notes':'valid',title:'Docker Compose file inspected',summary:`${services.length} service(s) found with ${findings.length} review note(s). Static inspection does not resolve interpolation or execute Compose.`,evidence:[{signal:'compose-services',source:'input',excerpt:services.map(([n])=>n).join(', ')},{signal:'top-level-sections',source:'input',excerpt:Object.keys(value).join(', ')}],findings,formatted};
 }catch(error){return {...base,status:'invalid',title:'Compose YAML could not be inspected',summary:error.message,actions:[],nextActions:['Correct the YAML/Compose structure and inspect again.']};}
}
