import YAML from 'yaml';
import resources from './resources.json';
const walkStats=(value,depth=0,seen=new Set())=>{const stats={depth,objects:0,arrays:0,primitives:0};if(value&&typeof value==='object'){if(seen.has(value))return stats;seen.add(value);if(Array.isArray(value))stats.arrays++;else stats.objects++;for(const child of Object.values(value)){const nested=walkStats(child,depth+1,seen);stats.depth=Math.max(stats.depth,nested.depth);stats.objects+=nested.objects;stats.arrays+=nested.arrays;stats.primitives+=nested.primitives;}}else stats.primitives++;return stats;};
const rootType=value=>value===null?'null':Array.isArray(value)?'array':typeof value;
const classify=value=>{if(!value||typeof value!=='object'||Array.isArray(value))return null;if('services' in value&&value.services&&typeof value.services==='object')return {kind:'compose',label:'Docker Compose-like configuration',evidence:['top-level services mapping']};if('apiVersion'in value&&'kind'in value&&'metadata'in value)return {kind:'kubernetes',label:'Kubernetes-like resource',evidence:['apiVersion, kind, and metadata fields']};return null;};
const base=(kind)=>({kind,status:'valid-with-notes',evidence:[],findings:[],actions:[{label:'Copy formatted output',type:'copy-output'}],checked:['Syntax parsing','Root value type','Basic structure statistics'],notChecked:resources.limitations,references:resources.references,nextActions:['Use the relevant product-specific tool for semantic validation.']});
export function analyzeJson(raw){
  const input=raw.replace(/^\uFEFF/,'');try{const value=JSON.parse(input);const stats=walkStats(value);return {...base('json'),title:'JSON parsed successfully',summary:`Root type: ${rootType(value)}. Depth ${stats.depth}; ${stats.objects} object(s), ${stats.arrays} array(s), ${stats.primitives} primitive value(s).`,evidence:[{signal:'strict-json-parse',source:'input',excerpt:'JSON.parse completed without an error.'}],formatted:JSON.stringify(value,null,2),compact:JSON.stringify(value),classification:classify(value)};}catch(error){return {...base('json'),status:'invalid',title:'JSON syntax error',summary:error.message,actions:[],nextActions:['Correct the JSON syntax and inspect it again.']};}
}
export function analyzeYaml(raw){
  const input=raw.replace(/^\uFEFF/,'');try{const docs=YAML.parseAllDocuments(input,{maxAliasCount:100,prettyErrors:true});const errors=docs.flatMap(doc=>doc.errors);if(errors.length)throw errors[0];if(docs.length>20)return {...base('yaml'),status:'unsupported',title:'Too many YAML documents',summary:'HelpDevOps analyzes at most 20 YAML documents at once.',actions:[],nextActions:['Split the input into smaller groups.']};const values=docs.map(doc=>doc.toJS({maxAliasCount:100}));const stats=values.reduce((total,value)=>{const s=walkStats(value);return {depth:Math.max(total.depth,s.depth),objects:total.objects+s.objects,arrays:total.arrays+s.arrays,primitives:total.primitives+s.primitives};},{depth:0,objects:0,arrays:0,primitives:0});const classification=values.map(classify).find(Boolean)||null;return {...base('yaml'),title:'YAML parsed successfully',summary:`${docs.length} document(s) parsed. Maximum depth ${stats.depth}; ${stats.objects} object(s), ${stats.arrays} array(s), ${stats.primitives} primitive value(s).`,evidence:[{signal:'yaml-parse',source:'input',excerpt:`${docs.length} document(s) parsed locally.`}],formatted:docs.map(doc=>doc.toString({indent:2})).join('---\n'),classification};}catch(error){return {...base('yaml'),status:'invalid',title:'YAML syntax error',summary:error.message,actions:[],nextActions:['Correct the YAML syntax and inspect it again.']};}
}
export function detectAndAnalyze(raw){
  const input=raw.replace(/^\uFEFF/,'');if(!input.trim())return {status:'invalid',kind:'unknown',title:'No input supplied',summary:'Paste JSON, YAML, or a common cron expression.',evidence:[],findings:[],actions:[],checked:['Empty input'],notChecked:resources.limitations,nextActions:['Paste input or load an example.']};
  if(new Blob([input]).size>262144)return {status:'unsupported',kind:'unknown',title:'Input is larger than 256 KB',summary:'The browser-first analyzer limits individual inputs to 256 KB.',evidence:[],findings:[],actions:[],checked:['Input size'],notChecked:['Content parsing was not attempted.'],nextActions:['Reduce the input size and try again.']};
  const json=analyzeJson(input);if(json.status!=='invalid')return json;
  try{const yaml=analyzeYaml(input);if(yaml.status!=='invalid'&&(/[:\-\[\]{}]/.test(input)||input.includes('\n')))return yaml;}catch{}
  return null;
}
