export const tools = [
  {id:'cron',title:'Cron Analyzer',path:'/tools/cron/',category:'Automation',capabilities:['INSPECT','VALIDATE'],inputKinds:['cron'],status:'available',description:'Inspect and explain common five-field cron schedules locally.',aliases:['crontab','schedule','job schedule']},
  {id:'structured-data',title:'JSON & YAML Inspector',path:'/tools/structured-data/',category:'Configuration',capabilities:['INSPECT','FORMAT'],inputKinds:['json','yaml'],status:'available',description:'Parse, inspect and safely format JSON or YAML in your browser.',aliases:['json formatter','yaml validator','format json','inspect yaml']},
  {id:'encoding-hash',title:'Encoding & Hash Workbench',path:'/tools/encoding-hash/',category:'Developer essentials',capabilities:['CONVERT','DECODE','CALCULATE'],inputKinds:['text-encoding','checksum'],status:'available',description:'Transform UTF-8 Base64, Base64URL, hex, URI components, and calculate SHA-2 hashes locally.',aliases:['base64','base64url','hex','sha256','sha384','sha512','uri component']},
  {id:'ipv4-cidr',title:'IPv4 CIDR Calculator',path:'/tools/ipv4-cidr/',category:'Networking',capabilities:['CALCULATE','INSPECT'],inputKinds:['cidr-ip'],status:'available',description:'Calculate IPv4 subnet boundaries and special-purpose classifications.',aliases:['subnet','network mask','wildcard mask','ipv4']},
  {id:'linux-permissions',title:'Linux Permissions Calculator',path:'/tools/linux-permissions/',category:'Linux',capabilities:['CALCULATE','INSPECT'],inputKinds:['linux-permissions'],status:'available',description:'Convert numeric and symbolic Unix permission bits with contextual cautions.',aliases:['chmod','octal','rwx','setuid','sticky bit']},
  {id:'git-reference',title:'Git Reference Toolkit',path:'/tools/git-reference/',category:'Git',capabilities:['VALIDATE','INSPECT'],inputKinds:['git-ref','git-revision'],status:'available',description:'Validate Git ref names and explain a conservative revision syntax subset.',aliases:['branch name','tag name','check-ref-format','gitrevisions']},
  {id:'docker-compose',title:'Docker Compose Analyzer',path:'/tools/',category:'Containers',capabilities:['INSPECT'],inputKinds:['compose'],status:'planned',description:'Detailed Docker Compose analysis is planned for a later EP.',aliases:['compose','docker compose']},
  {id:'kubernetes',title:'Kubernetes Manifest Analyzer',path:'/tools/',category:'Containers',capabilities:['INSPECT'],inputKinds:['kubernetes'],status:'planned',description:'Cluster-aware Kubernetes validation is planned for a later EP.',aliases:['k8s','manifest','kubectl']}
];
export const availableTools = tools.filter(tool => tool.status === 'available');
