import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('encoding and hashing operate locally', async ({ page }) => { await page.goto('/tools/encoding-hash/'); const input=page.locator('#encoding-input'); await input.fill('Hello 🌍'); await page.getByRole('button',{name:'Transform'}).click(); await expect(page.locator('[data-output]')).not.toBeEmpty(); await page.getByRole('button',{name:'Hash UTF-8'}).click(); await expect(page.locator('[data-output]')).toContainText('Hex:'); });
test('IPv4 calculator reports deterministic boundaries', async ({ page }) => { await page.goto('/tools/ipv4-cidr/'); await page.locator('#cidr-input').fill('192.168.1.34/24'); await page.getByRole('button',{name:'Calculate'}).click(); await expect(page.locator('[data-output]')).toContainText('Network: 192.168.1.0'); await expect(page.locator('[data-output]')).toContainText('Broadcast: 192.168.1.255'); });
test('Linux permissions handles special bits', async ({ page }) => { await page.goto('/tools/linux-permissions/'); await page.locator('#permissions-input').fill('4755'); await page.getByRole('button',{name:'Explain permissions'}).click(); await expect(page.locator('[data-output]')).toContainText('rwsr-xr-x'); });
test('Git toolkit separates syntax from repository resolution', async ({ page }) => { await page.goto('/tools/git-reference/'); await page.locator('#git-input').fill('refs/heads/main'); await page.locator('[data-mode]').selectOption('revision'); await page.getByRole('button',{name:'Analyze'}).click(); await expect(page.locator('[data-status]')).toContainText('fully qualified ref'); await expect(page.locator('[data-output]')).toContainText('Repository existence'); });
test('Universal Input routes exact EP-004 forms conservatively', async ({ page }) => { await page.goto('/'); const input=page.locator('#universal-input'); await input.fill('10.0.0.1/8'); await page.getByRole('button',{name:/Analyze input/}).click(); await expect(page.locator('[data-analysis-result]')).toContainText(/IPv4/i); await input.fill('deadbeef'); await page.getByRole('button',{name:/Analyze input/}).click(); await expect(page.getByText('Input was not recognized')).toBeVisible(); });
test('new tool pages are accessible and do not overflow on mobile', async ({ page }) => { await page.setViewportSize({width:390,height:844}); for(const route of ['/tools/encoding-hash/','/tools/ipv4-cidr/','/tools/linux-permissions/','/tools/git-reference/']){ await page.goto(route); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true); const result=await new AxeBuilder({page}).analyze(); expect(result.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]); } });
test('critical routes reflow at a 200 percent equivalent CSS viewport', async ({ page }) => { await page.setViewportSize({width:640,height:900}); for(const route of ['/','/tools/encoding-hash/','/tools/ipv4-cidr/','/tools/linux-permissions/','/tools/git-reference/']){ await page.goto(route); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true); } });
