import r0d from '../resources/references/linux-exit-signals/definition.json' with { type: 'json' };
import r0s from '../resources/references/linux-exit-signals/references.json' with { type: 'json' };
import r0e from '../resources/references/linux-exit-signals/examples.json' with { type: 'json' };
import r1d from '../resources/references/filesystem-blocks-inodes/definition.json' with { type: 'json' };
import r1s from '../resources/references/filesystem-blocks-inodes/references.json' with { type: 'json' };
import r1e from '../resources/references/filesystem-blocks-inodes/examples.json' with { type: 'json' };
import r2d from '../resources/references/systemd-service-states/definition.json' with { type: 'json' };
import r2s from '../resources/references/systemd-service-states/references.json' with { type: 'json' };
import r2e from '../resources/references/systemd-service-states/examples.json' with { type: 'json' };
import r3d from '../resources/references/shell-execution-context/definition.json' with { type: 'json' };
import r3s from '../resources/references/shell-execution-context/references.json' with { type: 'json' };
import r3e from '../resources/references/shell-execution-context/examples.json' with { type: 'json' };
import r4d from '../resources/references/cron-execution-environment/definition.json' with { type: 'json' };
import r4s from '../resources/references/cron-execution-environment/references.json' with { type: 'json' };
import r4e from '../resources/references/cron-execution-environment/examples.json' with { type: 'json' };
import r5d from '../resources/references/dns-resolution-layers/definition.json' with { type: 'json' };
import r5s from '../resources/references/dns-resolution-layers/references.json' with { type: 'json' };
import r5e from '../resources/references/dns-resolution-layers/examples.json' with { type: 'json' };
import r6d from '../resources/references/connection-refused-timeout/definition.json' with { type: 'json' };
import r6s from '../resources/references/connection-refused-timeout/references.json' with { type: 'json' };
import r6e from '../resources/references/connection-refused-timeout/examples.json' with { type: 'json' };
import r7d from '../resources/references/http-gateway-statuses/definition.json' with { type: 'json' };
import r7s from '../resources/references/http-gateway-statuses/references.json' with { type: 'json' };
import r7e from '../resources/references/http-gateway-statuses/examples.json' with { type: 'json' };
import r8d from '../resources/references/common-operational-ports/definition.json' with { type: 'json' };
import r8s from '../resources/references/common-operational-ports/references.json' with { type: 'json' };
import r8e from '../resources/references/common-operational-ports/examples.json' with { type: 'json' };
import r9d from '../resources/references/docker-container-states/definition.json' with { type: 'json' };
import r9s from '../resources/references/docker-container-states/references.json' with { type: 'json' };
import r9e from '../resources/references/docker-container-states/examples.json' with { type: 'json' };
import r10d from '../resources/references/kubernetes-pod-container-states/definition.json' with { type: 'json' };
import r10s from '../resources/references/kubernetes-pod-container-states/references.json' with { type: 'json' };
import r10e from '../resources/references/kubernetes-pod-container-states/examples.json' with { type: 'json' };
import r11d from '../resources/references/kubernetes-scheduling-evidence/definition.json' with { type: 'json' };
import r11s from '../resources/references/kubernetes-scheduling-evidence/references.json' with { type: 'json' };
import r11e from '../resources/references/kubernetes-scheduling-evidence/examples.json' with { type: 'json' };
import r12d from '../resources/references/git-local-remote-state/definition.json' with { type: 'json' };
import r12s from '../resources/references/git-local-remote-state/references.json' with { type: 'json' };
import r12e from '../resources/references/git-local-remote-state/examples.json' with { type: 'json' };
import r13d from '../resources/references/terraform-state-locking/definition.json' with { type: 'json' };
import r13s from '../resources/references/terraform-state-locking/references.json' with { type: 'json' };
import r13e from '../resources/references/terraform-state-locking/examples.json' with { type: 'json' };
export const operationalReferences=[{...r0d,references:r0s,examples:r0e},{...r1d,references:r1s,examples:r1e},{...r2d,references:r2s,examples:r2e},{...r3d,references:r3s,examples:r3e},{...r4d,references:r4s,examples:r4e},{...r5d,references:r5s,examples:r5e},{...r6d,references:r6s,examples:r6e},{...r7d,references:r7s,examples:r7e},{...r8d,references:r8s,examples:r8e},{...r9d,references:r9s,examples:r9e},{...r10d,references:r10s,examples:r10e},{...r11d,references:r11s,examples:r11e},{...r12d,references:r12s,examples:r12e},{...r13d,references:r13s,examples:r13e}].sort((a,b)=>a.title.localeCompare(b.title));
export const publishedReferences=operationalReferences.filter(item=>item.status==='reviewed');
export const referenceById=id=>operationalReferences.find(item=>item.id===id);
export const referenceDomains=[...new Set(publishedReferences.map(item=>item.domain))].sort();
