import YAML from 'yaml';
import resources from './resources.json';
const isObj=v=>v&&typeof v==='object'&&!Array.isArray(v);
const labelsMatch=(selector,labels)=>isObj(selector)&&Object.entries(selector).every(([k,v])=>labels?.[k]===v);
function podSpecOf(doc){if(doc.kind==='Pod')return doc.spec;if(['Deployment','StatefulSet','DaemonSet','ReplicaSet','Job'].includes(doc.kind))return doc.spec?.template?.spec;if(doc.kind==='CronJob')return doc.spec?.jobTemplate?.spec?.template?.spec;return null;}
function imageNote(image){if(typeof image!=='string'||image.includes('@sha256:'))return null;const last=image.split('/').at(-1);return !last.includes(':')||last.endsWith(':latest')?'image reference is unpinned or uses latest':null;}
export function analyzeKubernetes(raw){
 const base={kind:'kubernetes',evidence:[],findings:[],actions:[{label:'Review manifest findings',type:'review'}],checked:['YAML parsing','Core object identity fields','Selected workload pod-template structure','Selected security, image, resource and probe signals','Basic selector/template-label consistency for common workload kinds'],notChecked:resources.limitations,references:resources.references,nextActions:['Validate against the target cluster with server-side field validation before applying.','Use kubectl diff or an equivalent reviewed change preview.']};
 if(!raw.trim())return {...base,status:'invalid',title:'No Kubernetes manifest supplied',summary:'Paste one or more Kubernetes YAML documents.',actions:[]};
 if(new Blob([raw]).size>262144)return {...base,status:'unsupported',title:'Manifest input is larger than 256 KB',summary:'Reduce the input before local inspection.',actions:[]};
 try{const parsed=YAML.parseAllDocuments(raw,{maxAliasCount:100,prettyErrors:true});const yamlErrors=parsed.flatMap(d=>d.errors);if(yamlErrors.length)throw yamlErrors[0];if(parsed.length>20)return {...base,status:'unsupported',title:'Too many YAML documents',summary:'Inspect at most 20 manifest documents at once.',actions:[]};const docs=parsed.map(d=>d.toJS({maxAliasCount:100})).filter(v=>v!==null);const findings=[];const names=[];for(const [index,doc] of docs.entries()){const label=`Document ${index+1}`;if(!isObj(doc)){findings.push(`${label}: root is not a mapping.`);continue;}if(!doc.apiVersion)findings.push(`${label}: apiVersion is missing.`);if(!doc.kind)findings.push(`${label}: kind is missing.`);if(!isObj(doc.metadata))findings.push(`${label}: metadata mapping is missing.`);else if(!doc.metadata.name&&!doc.metadata.generateName)findings.push(`${label}: metadata.name or metadata.generateName is required for practical use.`);names.push(`${doc.kind||'Unknown'}/${doc.metadata?.name||doc.metadata?.generateName||'unnamed'}`);
 const podSpec=podSpecOf(doc);if(podSpec){if(!Array.isArray(podSpec.containers)||!podSpec.containers.length)findings.push(`${label}: workload pod specification has no containers.`);for(const [ci,c] of (podSpec.containers||[]).entries()){const cname=c?.name||`container-${ci+1}`;if(!c?.image)findings.push(`${label} ${cname}: image is missing.`);const note=imageNote(c?.image);if(note)findings.push(`${label} ${cname}: ${note} (${c.image}).`);if(c?.securityContext?.privileged===true)findings.push(`${label} ${cname}: privileged container can bypass normal container isolation.`);if(c?.securityContext?.allowPrivilegeEscalation===true)findings.push(`${label} ${cname}: allowPrivilegeEscalation is explicitly enabled.`);if(!c?.resources?.requests&&!c?.resources?.limits)findings.push(`${label} ${cname}: no resource requests or limits are declared.`);const probeExpected=!['Job','CronJob'].includes(doc.kind)&&!['Never','OnFailure'].includes(podSpec.restartPolicy);if(probeExpected&&!c?.readinessProbe&&!c?.livenessProbe&&!c?.startupProbe)findings.push(`${label} ${cname}: no readiness, liveness, or startup probe is declared for this long-running workload signal.`);}if(podSpec.hostNetwork===true)findings.push(`${label}: hostNetwork is enabled.`);if(podSpec.hostPID===true)findings.push(`${label}: hostPID is enabled.`);if(podSpec.hostIPC===true)findings.push(`${label}: hostIPC is enabled.`);for(const vol of podSpec.volumes||[])if(vol?.hostPath)findings.push(`${label}: volume ${vol.name||'unnamed'} uses hostPath ${vol.hostPath.path||''}.`);if(podSpec.securityContext?.runAsNonRoot!==true&&(podSpec.containers||[]).every(c=>c?.securityContext?.runAsNonRoot!==true))findings.push(`${label}: runAsNonRoot is not explicitly true at Pod or container level; the image may still define a non-root user.`);}
 if(['Deployment','StatefulSet','DaemonSet','ReplicaSet'].includes(doc.kind)){const selector=doc.spec?.selector?.matchLabels,labels=doc.spec?.template?.metadata?.labels;if(!isObj(selector)||!Object.keys(selector).length)findings.push(`${label}: spec.selector.matchLabels is missing or empty.`);else if(!labelsMatch(selector,labels))findings.push(`${label}: selector labels do not match the Pod template labels.`);}
 if(doc.kind==='Service'&&!isObj(doc.spec?.selector))findings.push(`${label}: Service has no selector; this may be intentional for manually managed endpoints.`);if(doc.kind==='Secret')findings.push(`${label}: Secret data was detected. HelpDevOps does not decode, validate, or store it automatically; avoid sharing sensitive manifests.`);
 }
 if(!docs.length)return {...base,status:'invalid',title:'No Kubernetes objects found',summary:'The YAML input did not contain an object.',actions:[]};const structural=findings.some(f=>/apiVersion is missing|kind is missing|metadata mapping is missing|root is not a mapping|has no containers/.test(f));return {...base,status:structural?'invalid':findings.length?'valid-with-notes':'valid',title:'Kubernetes manifests inspected',summary:`${docs.length} object(s) inspected with ${findings.length} review note(s). This is not cluster-aware schema validation.`,evidence:[{signal:'object-count',source:'input',excerpt:String(docs.length)},{signal:'object-identities',source:'input',excerpt:names.join(', ')}],findings,formatted:parsed.map(d=>d.toString({indent:2})).join('---\n')};
 }catch(error){return {...base,status:'invalid',title:'Kubernetes YAML could not be inspected',summary:error.message,actions:[],nextActions:['Correct the YAML structure and inspect again.']};}
}
