import {analyzeCron} from '../tools/cron/analyzer.js';
import {detectAndAnalyze} from '../tools/structured-data/analyzer.js';
import {calculateIPv4} from '../tools/ipv4-cidr/analyzer.js';import {analyzePermissions} from '../tools/linux-permissions/analyzer.js';import {validateRef} from '../tools/git-reference/analyzer.js';
export function analyzeInput(input){
  const structured=detectAndAnalyze(input);if(structured)return structured;
  const trimmed=input.trim();if(/^\d{1,3}(?:\.\d{1,3}){3}\/\d{1,2}$/.test(trimmed)){const value=calculateIPv4({cidr:trimmed});return value.status==='valid'?{...value,title:'IPv4 CIDR recognized',summary:`${value.address}/${value.prefix} belongs to network ${value.network}.`,evidence:[{signal:'exact-ipv4-cidr',source:'input',excerpt:trimmed}],findings:[],actions:[{label:'Open IPv4 calculator',type:'link'}],nextActions:['Open the IPv4 CIDR Calculator for full output.']}:value}if(/^[r-][w-][xSs-][r-][w-][xSs-][r-][w-][xTt-]$/.test(trimmed)){const value=analyzePermissions(trimmed);return{...value,title:'Symbolic Linux permissions recognized',evidence:[{signal:'nine-permission-positions',source:'input',excerpt:trimmed}],findings:[],actions:[],nextActions:['Open the Linux Permissions Calculator.']}}if(/^refs\/(heads|tags)\/.+/.test(trimmed)){const value=validateRef(trimmed,'full');return{...value,kind:'git-ref',summary:'This resembles a fully qualified Git ref. Repository resolution was not performed.',evidence:[{signal:'fully-qualified-ref',source:'input',excerpt:trimmed}],findings:value.diagnostics,actions:[],nextActions:['Open the Git Reference Toolkit.']}}
  const cron=analyzeCron(input);if(cron.status!=='invalid'||input.trim().split(/\s+/).length>=5)return cron;
  return {status:'unsupported',kind:'unknown',title:'Input was not recognized',summary:'The supplied text did not match the supported JSON, YAML, or common cron subsets.',evidence:[],findings:[],actions:[],checked:['JSON parse attempt','YAML parse attempt','Common five-field cron analysis'],notChecked:['Shell commands, logs, Dockerfiles, Jenkinsfiles, Terraform, and other planned domains'],nextActions:['Open the tools directory or try a supported example.']};
}
